language: cpp
dist: trusty
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev libqt5opengl5-dev libopenscenegraph-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
