language: cpp
dist: trusty
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libopenscenegraph-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
